config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "tweets#index"
  resources :tweets do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy, :index]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  has_one_attached :image

  validates :text, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_one_attached :image
  mount_uploader :video, VideoUploader

  def self.search(search)
    if search != ""
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end

  validates :text, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet

  def already_liked?(tweet_id)
    self.likes.exists?(tweet_id: tweet_id)
  end
  
  mount_uploader :avatar, AvatarUploader
  mount_uploader :header_image, AvatarUploader 

  validates :nickname, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.new(comment_params)
    if comment.save
      redirect_to tweet_path(comment.tweet)
    else
      @tweet = @comment.tweet
      @comments = @tweet.comments
      render "tweets/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :image).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def index
    @tweet = Tweet.find(params[:tweet_id])
    @likes = Like.all
  end

  def create
    @like = current_user.likes.create(tweet_id: params[:tweet_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :set_like, only: [:index, :show, :search]
  before_action :set_redirect, only: [:edit, :update, :destroy]
  

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user).order("created_at DESC")
  end

  def destroy
    @tweet.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweet_path
    else
      render :edit
    end
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  private
  def tweet_params
    params.require(:tweet).permit(:video, :image, :text).merge(user_id: current_user.id)
  end

  def set_redirect
    redirect_to root_path unless current_user.id == @tweet.user_id
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def set_like
    @likes = Like.all
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [:update]

 
  private
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :introduction, :avatar, :header_image])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update]
  before_action :set_user, only: [:show, :edit]

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      redirect_to edit_user_path(current_user.id)
    end
  end

  def show
    @tweets = @user.tweets.order("created_at DESC")
    @likes = Like.all
  end

  private
  def user_params
    params.require(:user).permit(:introduction, :nickname, :avatar, :header_image)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shares-みんなでシェアしよう-</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="//yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"></script>
    <script>
      new Darkmode().showWidget();
    </script>
    <%= yield %>
  </body>
</html>
  

app/views/likes/index.html.erb
<%= render "shared/header" %>


<div class="contents">
  <ul class='tweet-lists'>
    <h2><%= image_tag 'icon-253.png' , size: '30x30' ,class: "like-btn-icon2" %>
      したユーザー
    </h2>
    <% @tweet.liked_users.each do |user| %>
      <li class='tweet-list'>
        <%= link_to user_path(user), class: "no-underline" do %>
          <div class="like-content">
            <div class="user-image3">
              <% if user.avatar.present? %>
                <%= image_tag user.avatar.url, width: '100%', class: 'user-like-avatar' %>
              <% else %>
                <%= image_tag 'icon-258.png', width: '100%', class: 'user-like-avatar' %>
              <%end%>
            </div>
            <div class="content-user1">
              <p><%= user.nickname %><p>
            </div>
          </div>
          <div class="like-user-introduction">
            <p>自己紹介</p>
            <%= user.introduction %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class='footer'>
  <p>© SHARES</p>
</footer>

app/views/shared/_header.html.erb
<header class='heaher'>
  <%= image_tag 'icon-261.png' , size: '185x50' ,class: "icon" %>
  <%= link_to 'Shares', root_path, class: "type-icon" %>
</header>

app/views/shared/_icon.html.erb
<%if user_signed_in? %>
  <%= link_to(user_path(current_user.id), class: 'mipage-btn') do %>
    <div class='mipage-btn-text'>
      <%= current_user.nickname %>
    </div>
    <%= image_tag 'icon-252.png' , size: '185x50' ,class: "mipage-btn-icon" %>
  <% end %>
  <%= link_to(destroy_user_session_path, method: :delete, class: 'sign-up-btn') do %>
    <span class='sign-up-btn-text'>ログアウト</span>
    <%= image_tag 'icon-250.png' , size: '185x50' ,class: "sign-up-btn-icon" %>
  <% end %>
  <%= link_to(new_tweet_path, class: 'post-btn') do %>
    <span class='post-btn-text'>投稿する</span>
    <%= image_tag 'icon-261.png' , size: '185x50' ,class: "post-btn-icon" %>
  <% end %>
<% else %>
  <%= link_to(new_user_registration_path, class: 'registrations-btn') do %>
    <span class='registrations-btn-text'>新規登録</span>
    <%= image_tag 'icon-258.png' , size: '185x50' ,class: "registrations-btn-icon" %>
  <% end %>
  <%= link_to(new_user_session_path, class: 'mipage-btn') do %>
    <span class='mipage-btn-text'>マイページ</span>
    <%= image_tag 'icon-252.png' , size: '185x50' ,class: "mipage-btn-icon" %>
  <% end %>
  <%= link_to(new_user_session_path, class: 'logout-btn') do %>
    <span class='logout-btn-text'>ログイン</span>
    <%= image_tag 'icon-251.png' , size: '185x50' ,class: "logout-btn-icon" %>
  <% end %>
  <%= link_to(new_user_session_path, class: 'post-btn') do %>
    <span class='post-btn-text'>投稿する</span>
    <%= image_tag 'icon-261.png' , size: '185x50' ,class: "post-btn-icon" %>
  <% end %>
<% end %>

app/views/tweets/edit.html.erb
<%= render "shared/header" %>

<div class="box">
  <div class="box-inner">
    <%= form_with(model: @tweet, local: true) do |f| %>
      <h1>編集</h1>
      <%= render 'shared/error_messages', model: f.object %> 
      <div class="form-text">
        <%= f.text_area :text, class:"input", id:"text", placeholder:"例) おはよう！", autofocus: true %>
      </div>
      <div class="form-image">
        <label class="form-image-wrap">
          画像
        </label>
        <%= f.file_field :image, class: 'hidden' %>
      </div>
      <div class="from-video">
        <label class="form-video-wrap">
          動画
        </label>
        <%= f.file_field :video, :accept => 'video/*' %>
      </div>
      <div class="box-send">
        <%= f.submit "完了" %>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/tweets/index.html.erb
<%= render "shared/header" %>

<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |f| %>
  <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= f.submit "検索", class: "search-btn" %>
<% end %>

<div class="contents">
<ul class='tweet-lists'>
  <% @tweets.each do |tweet| %>
    <li class='tweet-list'>
      <%= link_to tweet_path(tweet.id), class: "no-underline" do %>
        <div class="upper-content">
          <div class="user-image1">
            <% if tweet.user.avatar.present? %>
              <%= image_tag tweet.user.avatar.url, width: '100%', class: 'user-avatar1' %>
            <% else %>
              <%= image_tag 'icon-258.png', width: '100%', class: 'user-avatar1' %>
            <%end%>
          </div>  
          <div class="content-user">
            <%= tweet.user.nickname %>
          </div>
          <div class="content-date">
            <%= tweet.created_at %>
          </div>
        </div>
        <div class="lower-content">
          <div class="content-tweet">
            <%= tweet.text %>
          </div>
          <%= image_tag tweet.image.variant(resize: '450x450'), class: 'tweet-image' if tweet.image.attached? %>
        </div>
          <%= link_to tweet.video_url.to_s do %>
            <%= video_tag tweet.video.to_s, size: '400x400', controls: true, autobuffer: true, class: 'tweet-video' if tweet.video.present? %>
          <% end %>
        <div class="likes-count">
          <% if current_user %>
            <% if current_user.already_liked?(tweet) %>
              <%= link_to tweet_like_path(tweet, @likes.ids), method: :delete, class: "like-button" do %>
                <%= image_tag 'icon-253.png' , size: '25x25' ,class: "like-btn-icon" %>
                <div class="like-math">
                  <%= tweet.likes.count %>
                </div>
              <% end %>
            <% else %>
              <%= link_to tweet_likes_path(tweet), method: :post, class: "like-button" do %>
                <%= image_tag 'icon-253.png' , size: '25x25' ,class: "like-btn-icon" %>
                <div class="like-math">
                  <%= tweet.likes.count %>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path, method: :post, class: "like-button" do %>
              <%= image_tag 'icon-253.png' , size: '25x25' ,class: "like-btn-icon" %>
              <div class="like-math">
                <%= tweet.likes.count %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </li>
    <div class="margin"></div>
  <% end %>
</ul>
</div>

<%= render "shared/icon" %>

<%= render "shared/footer" %>

app/views/tweets/new.html.erb
<%= render "shared/header" %>

<div class="box2">
  <div class="box-inner">
    <%= form_with model: @tweet, url: tweets_path, class: 'registration-main', local: true do |f| %>
      <h1>投稿</h1>
      <%= render 'shared/error_messages', model: f.object %> 
      <div class="form-text">
        <%= f.text_area :text, class:"input", id:"text", placeholder:"例) おはよう！", autofocus: true %>
      </div>
      <div class="form-image">
        <label class="form-image-wrap">
          画像
        </label>
        <%= f.file_field :image, class: 'hidden'%>
      </div>
      <div class="from-video">
        <label class="form-video-wrap">
          動画
        </label>
        <%= f.file_field :video, :accept => 'video/*' %>
      </div>
      <div class="box-send">
        <%= f.submit "投稿" %>
      </div>
    <% end %>
  </div>
</div>


<%= render "shared/footer" %>

app/views/tweets/search.html.erb
<%= render "shared/header" %>

<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |f| %>
  <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= f.submit "検索", class: "search-btn" %>
<% end %>

<div class="contents">
<ul class='tweet-lists'>
  <% @tweets.each do |tweet| %>
    <li class='tweet-list'>
      <%= link_to tweet_path(tweet.id), class: "no-underline" do %>
        <div class="upper-content">
          <div class="user-image1">
            <% if tweet.user.avatar.present? %>
              <%= image_tag tweet.user.avatar.url, width: '100%', class: 'user-avatar1' %>
            <% else %>
              <%= image_tag 'icon-258.png', width: '100%', class: 'user-avatar1' %>
            <%end%>
          </div>  
          <div class="content-user">
            <%= tweet.user.nickname %>
          </div>
          <div class="content-date">
            <%= tweet.created_at %>
          </div>
        </div>
        <div class="lower-content">
          <div class="content-tweet">
            <%= tweet.text %>
          </div>
          <%= image_tag tweet.image.variant(resize: '450x450'), class: 'tweet-image' if tweet.image.attached? %>
        </div>
        <%= link_to tweet.video_url.to_s do %>
          <%= video_tag tweet.video.to_s, size: '400x400', controls: true, autobuffer: true, class: 'tweet-video' if tweet.video.present? %>
        <% end %>
        <div class="likes-count">
          <% if current_user %>
            <% if current_user.already_liked?(tweet) %>
              <%= link_to tweet_like_path(tweet, @likes.ids), method: :delete, class: "like-button" do %>
                <%= image_tag 'icon-253.png' , size: '25x25' ,class: "like-btn-icon" %>
                <div class="like-math">
                  <%= tweet.likes.count %>
                </div>
             <% end %>
            <% else %>
              <%= link_to tweet_likes_path(tweet), method: :post, class: "like-button" do %>
                <%= image_tag 'icon-253.png' , size: '25x25' ,class: "like-btn-icon" %>
                <div class="like-math">
                  <%= tweet.likes.count %>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path, method: :post, class: "like-button" do %>
               <%= image_tag 'icon-253.png' , size: '25x25' ,class: "like-btn-icon" %>
              <div class="like-math">
                <%= tweet.likes.count %>
              </div>
             <% end %>
          <% end %>
        </div>
      <% end %>
    </li>
    <div class="margin"></div>
  <% end %>
</ul>
</div>

<%= render "shared/icon" %>

<%= render "shared/footer" %>

app/views/tweets/show.html.erb
<%= render "shared/header" %>

<div class="contents">
  <ul class='tweet-lists'>
      <li class='tweet-list1'>
        <%= link_to user_path(@tweet.user), class: "no-underline" do %>
          <div class="upper-content">
            <div class="user-image1">
              <% if @tweet.user.avatar.present? %>
                <%= image_tag @tweet.user.avatar.url, width: '100%', class: 'user-avatar1' %>
              <% else %>
                <%= image_tag 'icon-258.png', width: '100%', class: 'user-avatar1' %>
              <%end%>
            </div>  
            <div class="content-user">
              <%= @tweet.user.nickname %>
            </div>
            <div class="content-date">
              <%= @tweet.created_at %>
            </div>
          </div>
          <div class="lower-content">
            <div class="content-tweet">
              <%= @tweet.text %>
            </div>
            <%= image_tag @tweet.image.variant(resize: '450x450'), class: 'tweet-image' if @tweet.image.attached? %>
          </div>
          <%= link_to @tweet.video_url.to_s do %>
            <%= video_tag @tweet.video.to_s, size: '400x400', controls: true, autobuffer: true, class: 'tweet-video' if @tweet.video.present? %>
          <% end %>
          <div class="likes-count">
            <% if current_user %>
              <%= link_to tweet_likes_path(@tweet, @likes.ids), class: "like-button" do %>
                <%= image_tag 'icon-253.png' , size: '25x25' ,class: "like-btn-icon" %>
                <div class="like-math">
                  <%= @tweet.likes.count %>
                </div>
              <% end %>
            <% else %>
              <%= link_to new_user_session_path, method: :post, class: "like-button" do %>
                <%= image_tag 'icon-253.png' , size: '25x25' ,class: "like-btn-icon" %>
                <div class="like-math">
                  <%= @tweet.likes.count %>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </li>
      <div class="margin"></div>
  </ul>

  <%if user_signed_in? %>
    <% if current_user.id == @tweet.user_id %>
      <%= link_to "編集", edit_tweet_path(@tweet.id), method: :get, class: "tweet-blue-btn" %>
      <%= link_to "削除", tweet_path(@tweet.id), method: :delete, class:"tweet-destroy" %>
    <% end %>
    
    <%= form_with model: [@tweet, @comment], local: true do |f| %>
      <div class="field">
        <%= f.text_area :text, class: "input-area", id:"text", placeholder:"コメント", autofocus: true %>
        <div class="box-image">
          <div class="form-image">
            <label class="form-image-wrap">
              <%= f.file_field :image, class: 'hidden' %>
            </label>
          </div>
          <%= f.submit "送信する", class: "form__btn"  %>
        </div>
      </div>
    <% end %> 

  <% end %> 
  <ul class="comments_lists">
  <p class='info-comment'>------コメント一覧------</p>
    <% @comments.each do |comment| %>
      <li class="comments_list">
        <div class="user-image2">
          <% if comment.user.avatar.present? %>
            <%= image_tag comment.user.avatar.url, width: '100%', class: 'user-avatar2' %>
          <% else %>
            <%= image_tag 'icon-258.png', width: '100%', class: 'user-avatar2' %>
          <%end%>
        </div>  
        <%= link_to "#{comment.user.nickname}", "/users/#{comment.user_id}", class: "comment_user" %>
          <div class="upper-comment">
            <%= comment.text %>
            <div class="lower-comment">
              <%= image_tag comment.image.variant(resize: '200x200'), class: 'comment-image' if comment.image.attached? %>
            </div>
          </div>
      </li>
    <% end %>
  </ul>
</div>

<%= render "shared/icon" %>

<%= render "shared/footer" %>

app/views/users/edit.html.erb
<%= render "shared/header" %>
<div class="box">
  <div class="box-inner">
    <%= form_with(model: @user, local: true) do |f| %>
      <h1>ユーザー編集</h1>
      <div class="form-edit">
        <div class='form-avatar-wrap'>
          <label class="form-avatar-text">トップ画像</label>
        </div>
        <%= f.file_field :avatar, class:"input-avatar", id:"avatar" %>
        <div class='form-header_image-wrap'>
          <label class="form-header_image-text">ヘッター画像</label>
        </div>
        <%= f.file_field :header_image, class:"input-header_image", id:"header_image" %>
        <div class='form-edit-wrap'>
          <label class="form-edit-text">ニックネーム</label>
        </div>
        <%= f.text_field :nickname, class:"input", id:"nickname", autofocus: true %>
      </div>
      <div class="form-introduction">
          <div class='form-introduction-wrap'>
            <label class="form-introduction-text">自己紹介</label>
          </div>
        <%= f.text_area :introduction, class:"input-default", id:"introduction", autcomplete: "off" %>
      </div>
      <div class="box-login">
        <%= f.submit "完了" %>
      </div>
    <% end %>
  </div>
</div>


<%= render "shared/footer" %>

app/views/users/show.html.erb
<% if @user.header_image.present? %>
  <header class='user-heaher'>
    <%= image_tag @user.header_image.url, width: '100%', class: 'user-header_image' %>
  </header>
<% else %>
  <%= render "shared/header" %>
<%end%>


<div class="information">
  <div class="user-image">
    <% if @user.avatar.present? %>
      <%= image_tag @user.avatar.url, width: '100%', class: 'user-avatar' %>
    <% else %>
      <%= image_tag 'icon-258.png', width: '100%', class: 'user-avatar' %>
    <%end%>
  </div>
  <div class="user-nickname">
    <%= @user.nickname %>
  </div>
  <% if current_user.id == @user.id %>
    <%=link_to '変更', edit_user_path(@user.id), class: "change" %>
  <% end %>
</div>
<div class="user-introduction">
  <p>自己紹介</p>
  <%= @user.introduction %>
</div>

<div class="contents">
<ul class='tweet-lists'>
  <% @tweets.each do |tweet| %>
    <li class='tweet-list'>
      <%= link_to tweet_path(tweet.id), class: "no-underline" do %>
        <div class="upper-content">
          <div class="user-image1">
            <% if tweet.user.avatar.present? %>
              <%= image_tag tweet.user.avatar.url, width: '100%', class: 'user-avatar1' %>
            <% else %>
              <%= image_tag 'icon-258.png', width: '100%', class: 'user-avatar1' %>
            <%end%>
          </div>  
          <div class="content-user">
            <%= tweet.user.nickname %>
          </div>
          <div class="content-date">
            <%= tweet.created_at %>
          </div>
        </div>
        <div class="lower-content">
          <div class="content-tweet">
            <%= tweet.text %>
          </div>
          <%= image_tag tweet.image.variant(resize: '450x450'), class: 'tweet-image' if tweet.image.attached? %>
        </div>
        <%= link_to tweet.video_url.to_s do %>
          <%= video_tag tweet.video.to_s, size: '400x400', controls: true, autobuffer: true, class: 'tweet-video' if tweet.video.present? %>
        <% end %>
        <div class="likes-count">
          <% if current_user %>
            <% if current_user.already_liked?(tweet) %>
              <%= link_to tweet_like_path(tweet, @likes.ids), method: :delete, class: "like-button" do %>
                <%= image_tag 'icon-253.png' , size: '25x25' ,class: "like-btn-icon" %>
                <div class="like-math">
                  <%= tweet.likes.count %>
                </div>
              <% end %>
            <% else %>
              <%= link_to tweet_likes_path(tweet), method: :post, class: "like-button" do %>
                <%= image_tag 'icon-253.png' , size: '25x25' ,class: "like-btn-icon" %>
                <div class="like-math">
                  <%= tweet.likes.count %>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path, method: :post, class: "like-button" do %>
              <%= image_tag 'icon-253.png' , size: '25x25' ,class: "like-btn-icon" %>
              <div class="like-math">
                <%= tweet.likes.count %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </li>
    <div class="margin"></div>
  <% end %>
</ul>
</div>

<%if user_signed_in? %>
  <% if current_user.id != @user.id %>
    <%= link_to(user_path(current_user.id), class: 'mipage-btn') do %>
      <div class='mipage-btn-text'>
        <%= current_user.nickname %>
      </div>
      <%= image_tag 'icon-252.png' , size: '185x50' ,class: "mipage-btn-icon" %>
    <% end %>
  <% else %>
    <%= link_to(root_path, class: 'mipage-btn') do %>
      <span class='mipage-btn-text'>トップ</span>
      <%= image_tag 'icon-252.png' , size: '185x50' ,class: "mipage-btn-icon" %>
    <% end %>
  <% end %>
  <%= link_to(destroy_user_session_path, method: :delete, class: 'sign-up-btn') do %>
    <span class='sign-up-btn-text'>ログアウト</span>
    <%= image_tag 'icon-250.png' , size: '185x50' ,class: "sign-up-btn-icon" %>
  <% end %>
  <%= link_to(new_tweet_path, class: 'post-btn') do %>
    <span class='post-btn-text'>投稿する</span>
    <%= image_tag 'icon-261.png' , size: '185x50' ,class: "post-btn-icon" %>
  <% end %>
<% else %>
  <%= link_to(new_user_registration_path, class: 'registrations-btn') do %>
    <span class='registrations-btn-text'>新規登録</span>
    <%= image_tag 'icon-258.png' , size: '185x50' ,class: "registrations-btn-icon" %>
  <% end %>
  <%= link_to(new_user_session_path, class: 'mipage-btn') do %>
    <span class='mipage-btn-text'>マイページ</span>
    <%= image_tag 'icon-252.png' , size: '185x50' ,class: "mipage-btn-icon" %>
  <% end %>
  <%= link_to(new_user_session_path, class: 'logout-btn') do %>
    <span class='logout-btn-text'>ログイン</span>
    <%= image_tag 'icon-251.png' , size: '185x50' ,class: "logout-btn-icon" %>
  <% end %>
  <%= link_to(new_user_session_path, class: 'post-btn') do %>
    <span class='post-btn-text'>投稿する</span>
    <%= image_tag 'icon-261.png' , size: '185x50' ,class: "post-btn-icon" %>
  <% end %>
<% end %>


<%= render "shared/footer" %>